### ISSUE TITLE
Scroll duration and scroll transition functions

### ISSUE THREAD

**Issue by M00nD3v** [three11/scrollspy#373]
First of all thank you for this simple but awesome module.

It would be awesome, if I were able to set the scroll-duration and a scroll timing function like `ease-in-out` etc. Currently the scrolling of smaller distances is very abruptly and therefore feels unnaturally and not fluent.

Cheers!

**Comment by scriptex** [comment]
That's actually a really good feedback! Thanks @M00nD3v! I will try to find some time to implement this.

**Comment by scriptex** [comment]
@M00nD3v  I have released a new version of the module.
You can download it from [NPM](https://www.npmjs.com/package/@three11/scrollspy) or [Github](https://github.com/three11/scrollspy/releases/tag/2.0.0)

For more details about the new configuration options please consult the [documentation](https://github.com/three11/scrollspy#usage).

If you need more details, don't hesitate to ping me :)

Once again thanks for the feedback!
